import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#a31b1f",
        "on-secondary-container": "#666161",
        "outline": "#8e706d",
        "on-surface-variant": "#5a413e",
        "tertiary-fixed-dim": "#8fcdfb",
        "primary": "#7f000d",
        "surface-tint": "#b32829",
        "inverse-primary": "#ffb3ad",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ad",
        "secondary-fixed": "#e8e1e0",
        "error-color": "#ba1a1a",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#4a4646",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e2bebb",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#910914",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ccc5c5",
        "surface-container": "#eeeeee",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed": "#001e2f",
        "tertiary": "#00415f",
        "secondary-container": "#e5dede",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "tertiary-container": "#005981",
        "surface-variant": "#e2e2e2",
        "background": "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-primary-container": "#ffb5ae",
        "on-surface": "#1a1c1c",
        "on-primary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-background": "#1a1c1c",
        "secondary": "#625d5d",
        "on-secondary-fixed": "#1e1b1b",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary-container": "#90cffd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
