"""add hint to exercises and app_settings table

Revision ID: 39cfcc5e890d
Revises: c78969f7e469
Create Date: 2026-04-13 20:47:44.192109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39cfcc5e890d'
down_revision: Union[str, None] = 'c78969f7e469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'hint')
    # ### end Alembic commands ###
