"""add_exam_mode_to_sessions

Revision ID: 86cdd0c8c6e5
Revises: 39cfcc5e890d
Create Date: 2026-04-13 21:22:16.777600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86cdd0c8c6e5'
down_revision: Union[str, None] = '39cfcc5e890d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('exam_mode', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'exam_mode')
    # ### end Alembic commands ###
