"""add_subject_filetype_topiclist

Revision ID: c78969f7e469
Revises: 
Create Date: 2026-04-13 15:21:23.113612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c78969f7e469'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('subject', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.String(length=32), nullable=False, server_default='other'))
    op.add_column('study_sessions', sa.Column('topic_filter', sa.JSON(), nullable=True))
    op.create_table(
        'subject_topic_lists',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('subject', sa.String(length=64), nullable=False, unique=True),
        sa.Column('topics_json', sa.Text(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=False),
        sa.Column('source_doc_ids', sa.Text(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_topic_lists')
    op.drop_column('study_sessions', 'topic_filter')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'subject')
    # ### end Alembic commands ###
