"""add exam profiles

Revision ID: db69bb333459
Revises: ef05a6ac85f4
Create Date: 2026-04-14 15:23:40.151106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db69bb333459'
down_revision: Union[str, None] = 'ef05a6ac85f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('question_type_distribution', sa.Text(), nullable=False),
    sa.Column('style_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_profiles_subject'), 'exam_profiles', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_profiles_subject'), table_name='exam_profiles')
    op.drop_table('exam_profiles')
    # ### end Alembic commands ###
