"""add_pre_generated_to_sessions

Revision ID: ef05a6ac85f4
Revises: 86cdd0c8c6e5
Create Date: 2026-04-14 11:16:32.887460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef05a6ac85f4'
down_revision: Union[str, None] = '86cdd0c8c6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('pre_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'pre_generated')
    # ### end Alembic commands ###
